### ISSUE TITLE
cycle-storage-driver v1.0.0

### ISSUE THREAD

**Issue by khalillechelt** [kahlil/cycle-storage-driver#1]
The list of things to be done before the initial release:
- [x] write readme https://github.com/kahlil/cycle-storage-driver/issues/2
- [x] add simple example https://github.com/kahlil/cycle-storage-driver/issues/3
- [x] add testing with sauce labs https://github.com/kahlil/cycle-storage-driver/issues/4
- [x] write API docs https://github.com/kahlil/cycle-storage-driver/issues/5
- [x] add dist build #6 
- [x] @staltz should review if requirements are fulfilled according to https://github.com/cyclejs/cycle-core/issues/141 (optional) 
- [x] inquire with @staltz if this should be under @cyclejs GitHub org (optional)

**Comment by khalillechelt** [comment]
Hi @staltz as mentioned in the todos above it would be great if you could look over the code and see if the work has been done according to the requirements of https://github.com/cyclejs/cycle-core/issues/141. 

And also as mentioned above: let me know if you would like to have this under @cyclejs, I am happy to transfer it to the org once it is ready (same goes for npm).

**Comment by staltz** [comment]
@kahlil sorry for the delay in answering you. This looks perfect.

Let's put it in the cyclejs org? And in npm as well.

**Comment by khalillechelt** [comment]
@staltz no problem, yep happy to transfer it. I'll take care of that today. 

Should the npm package name then be changed to @cycle/storage or something or leave as is?

**Comment by staltz** [comment]
`@cycle/storage` :+1:

**Comment by khalillechelt** [comment]
@staltz OK I added the `cycle` user as a collaborator on npm but I can not publish it under the cycle-scope. I guess you will have to do that?

**Comment by staltz** [comment]
It usually goes like this: you change the package name to be `@cycle/storage`, I have to publish it on npm with that name, then on the npmjs website I add you as collaborator, then you get to do subsequent publishes. Can you transfer this repo also to cyclejs github org?

**Comment by khalillechelt** [comment]
This repo is under cyclejs github org as we speak :smile: 

I changed the package name. You can go ahead and publish to npm.

**Comment by staltz** [comment]
lol, sorry

**Comment by staltz** [comment]
Done

**Comment by khalillechelt** [comment]
\o/ awesome!
